apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-world-deployment
  labels:
    app: springboot-hello-world
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: springboot-hello-world
  template:
    metadata:
      labels:
        app: springboot-hello-world
    spec:
      containers:
        - name: springboot-hello-world
          image: mypoccontainerregistry.azurecr.io/springboot-hello-world:latest
          ports:
            - containerPort: 8080
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: springboot-hello-worldloadbalancer-service
#  labels:
#    app: springboot-hello-world
#spec:
#  type: LoadBalancer
#  selector:
#    app: springboot-hello-world
#  ports:
#    - port: 8080
#      targetPort: 8080